{{- if and .Values.credentials.name (not .Values.credentials.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "powerdns-operator.labels" . | nindent 4 }}
  name: {{ include "powerdns-operator.credentials.name" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- range $key, $value := .Values.credentials.data }}
  {{ $key }}: {{ tpl $value $ | b64enc | quote }}
{{- end }}
{{- end -}}